### ISSUE TITLE
Cannot access tiles generated in edit mode

### ISSUE THREAD

**Issue by Gravn** [Amaranthos/UnityHexGrid#2]
Cannot access tiles generated in edit mode, i disabled generation on Awake(), as i have generated tiles in edit mode. Now i get a NullReferenceException for "public List<Tile> Neighbours(Tile tile)" at o = tile.index + directions[i].

Works if tiles are generated on runtime.

**Comment by Amaranthos** [comment]
That would suggest that the tile you are passing to Neighbours() is null. The method `public List Neighbours(Tile tile)` should be updated to include a null check for the tile passed in and return the empty list if so. Feel free to raise a pr
