### ISSUE TITLE
Generate Grid in runTime as default

### ISSUE THREAD

**Issue by ConnorTheCone** [Amaranthos/UnityHexGrid#5]
Seems like the Grid script is generating the grid in the awake, is this intended? 

https://github.com/Amaranthos/UnityHexGrid/blob/e66771c0c54eb64b825ab57ad112d6595c020ccf/HexGrid/Assets/Grid.cs#L159

**Comment by Amaranthos** [comment]
Yep, it was intended in the project that this library was written for
